### ISSUE TITLE
Cannot find the weight

### ISSUE THREAD

**Issue by akaljotdhillon** [knowledgedefinednetworking/a-deep-rl-approach-for-sdn-routing-optimization#5]
When I run ddpg.py It says unable to find the weight. I have confusion where to place file "traffic" that contains 1000 TMs.

**Comment by adikolsur** [comment]
How did you solve this issue? Facing the same problem while running ddpg.py. @akaljotdhillon

**Comment by wqhcug** [comment]
Sorry, no&nbsp;&nbsp;solution.
Because the author&nbsp; did not explain the problem or I did not notice it.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Aditya Kolsur"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月17日(星期二) 晚上8:02
收件人:&nbsp;"knowledgedefinednetworking/a-deep-rl-approach-for-sdn-routing-optimization"<a-deep-rl-approach-for-sdn-routing-optimization@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [knowledgedefinednetworking/a-deep-rl-approach-for-sdn-routing-optimization] Cannot find the weight (#5)





 
How did you solve this issue? Facing the same problem while running ddpg.py
